// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class Test4CreateDepositTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test4CreateDeposit() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    
    // Navigate to application
    driver.get("http://34.42.31.237:8080/");
    driver.manage().window().setSize(new Dimension(968, 877));
    
    // Login
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    driver.findElement(By.cssSelector("input[type='text']")).click();
    driver.findElement(By.cssSelector("input[type='text']")).sendKeys("testuser");
    driver.findElement(By.cssSelector("input[type='password']")).click();
    driver.findElement(By.cssSelector("input[type='password']")).sendKeys("password123");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    
    // Wait for dashboard to load
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".page-title")));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".acct")));
    
    // Select first account
    driver.findElement(By.cssSelector(".acct:first-child")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".detail-actions")));
    
    // Click "New Transaction" button
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".btn-secondary:nth-child(2)")));
    driver.findElement(By.cssSelector(".btn-secondary:nth-child(2)")).click();
    
    // Wait for transaction form to appear
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".transaction-form")));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".transaction-form select")));
    
    // Select DEPOSIT from transaction type dropdown
    WebElement transactionTypeSelect = driver.findElement(By.cssSelector(".transaction-form select"));
    transactionTypeSelect.click();
    transactionTypeSelect.findElement(By.cssSelector("option[value='DEPOSIT']")).click();
    
    // Wait for amount input (for deposit, it's the second form-group)
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".transaction-form input[type='number']")));
    driver.findElement(By.cssSelector(".transaction-form input[type='number']")).click();
    driver.findElement(By.cssSelector(".transaction-form input[type='number']")).sendKeys("100.00");
    
    // Optional: Add description
    WebElement descriptionInput = driver.findElement(By.cssSelector(".transaction-form input[type='text'][placeholder*='description']"));
    if (descriptionInput.isDisplayed()) {
      descriptionInput.click();
      descriptionInput.sendKeys("Selenium test deposit");
    }
    
    // Submit the form
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".transaction-form button[type='submit']")));
    driver.findElement(By.cssSelector(".transaction-form button[type='submit']")).click();
    
    // Wait for success message
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".alert-success")));
    
    // Verify success
    WebElement successAlert = driver.findElement(By.cssSelector(".alert-success"));
    assertTrue(successAlert.isDisplayed());
    
    // Logout
    driver.findElement(By.cssSelector(".logout-btn")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".login-container")));
    
    driver.close();
  }
}
