// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test3ViewTransactionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test3ViewTransactions() {
    driver.get("http://34.42.31.237:8080/");
    driver.manage().window().setSize(new Dimension(968, 877));
    driver.findElement(By.cssSelector(".input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".input:nth-child(2)")).sendKeys("testuser");
    driver.findElement(By.cssSelector(".input:nth-child(2)")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".input:nth-child(1)")).sendKeys("password123");
    driver.findElement(By.cssSelector(".input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".quick-filter-btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".quick-filter-btn:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".quick-filter-btn:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".quick-filter-btn:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".quick-filter-btn:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".logout-btn")).click();
    driver.close();
  }
}
