// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import io.github.bonigarcia.wdm.WebDriverManager;
public class Test4CreateDepositTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    options.addArguments("--no-sandbox");
    options.addArguments("--disable-dev-shm-usage");
    options.addArguments("--disable-gpu");
    options.addArguments("--window-size=1920,1080");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test4CreateDeposit() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    
    // Navigate to application
    driver.get("http://34.42.31.237:8080/");
    driver.manage().window().setSize(new Dimension(968, 877));
    
    // Wait for login page and login as ADMIN user (needed to see DEPOSIT option)
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    WebElement usernameInput = driver.findElement(By.cssSelector("input[type='text']"));
    usernameInput.click();
    usernameInput.clear();
    usernameInput.sendKeys("adminuser"); // Use admin user to see DEPOSIT option
    
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='password']")));
    WebElement passwordInput = driver.findElement(By.cssSelector("input[type='password']"));
    passwordInput.click();
    passwordInput.clear();
    passwordInput.sendKeys("admin123");
    
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button[type='submit']")));
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    
    // Wait for dashboard to load
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".page-title")));
    
    // Check if admin user has accounts, if not create one
    boolean hasAccounts = false;
    try {
      // Wait a bit to see if accounts load
      try {
        Thread.sleep(2000);
      } catch (InterruptedException ie) {
        Thread.currentThread().interrupt();
      }
      // Check if any account elements exist
      java.util.List<WebElement> accounts = driver.findElements(By.cssSelector(".acct"));
      if (accounts.size() > 0 && !accounts.get(0).getText().contains("No accounts")) {
        hasAccounts = true;
      }
    } catch (Exception e) {
      // No accounts found
      hasAccounts = false;
    }
    
    if (!hasAccounts) {
      // No accounts found, create one first
      System.out.println("No accounts found, creating account first...");
      
      // Click "New Account" button (button with text "New Account" in card-head)
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".card-head")));
      java.util.List<WebElement> buttons = driver.findElements(By.cssSelector(".card-head .btn-secondary"));
      for (WebElement btn : buttons) {
        if (btn.getText().contains("New Account") || btn.getText().contains("Account")) {
          wait.until(ExpectedConditions.elementToBeClickable(btn));
          btn.click();
          break;
        }
      }
      
      // Wait for account form (it uses transaction-form class)
      WebDriverWait formWait = new WebDriverWait(driver, Duration.ofSeconds(15));
      formWait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".transaction-form")));
      formWait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".transaction-form select")));
      
      // Select account type
      WebElement accountTypeSelect = driver.findElement(By.cssSelector(".transaction-form select"));
      Select accountSelect = new Select(accountTypeSelect);
      accountSelect.selectByValue("CHECKING");
      
      // Submit account creation
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".transaction-form button[type='submit']")));
      driver.findElement(By.cssSelector(".transaction-form button[type='submit']")).click();
      
      // Wait for success and account to appear (with longer timeout)
      WebDriverWait longWait = new WebDriverWait(driver, Duration.ofSeconds(20));
      longWait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".alert-success")));
      try {
        Thread.sleep(2000); // Give time for account to appear in list
      } catch (InterruptedException ie) {
        Thread.currentThread().interrupt();
      }
      longWait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".acct")));
    }
    
    // Now select the first account
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".acct:first-child")));
    driver.findElement(By.cssSelector(".acct:first-child")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".detail-actions")));
    
    // Click "New Transaction" button
    // The button is in .detail-actions, second button (index 1)
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".detail-actions")));
    java.util.List<WebElement> detailButtons = driver.findElements(By.cssSelector(".detail-actions .btn"));
    WebElement newTransactionBtn = null;
    for (WebElement btn : detailButtons) {
      if (btn.getText().contains("New Transaction") || btn.getText().contains("Transaction")) {
        newTransactionBtn = btn;
        break;
      }
    }
    if (newTransactionBtn == null) {
      // Fallback to second button
      newTransactionBtn = detailButtons.get(1);
    }
    wait.until(ExpectedConditions.elementToBeClickable(newTransactionBtn));
    newTransactionBtn.click();
    
    // Wait for transaction form to appear (with longer timeout)
    WebDriverWait formWait = new WebDriverWait(driver, Duration.ofSeconds(15));
    formWait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".transaction-form")));
    formWait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".transaction-form select")));
    
    // Select DEPOSIT from transaction type dropdown
    WebElement transactionTypeSelect = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".transaction-form select")));
    // Use Select class for better dropdown handling
    Select select = new Select(transactionTypeSelect);
    wait.until(ExpectedConditions.elementToBeClickable(transactionTypeSelect));
    
    // Wait for options to be available, then select by visible text (more reliable)
    wait.until(ExpectedConditions.presenceOfNestedElementLocatedBy(transactionTypeSelect, By.cssSelector("option")));
    
    // Try to select by visible text first (works for both admin and customer)
    try {
      select.selectByVisibleText("Deposit");
    } catch (Exception e) {
      // If Deposit not available (customer role), try by value
      try {
        select.selectByValue("DEPOSIT");
      } catch (Exception e2) {
        // If still fails, list available options for debugging
        java.util.List<WebElement> options = select.getOptions();
        System.out.println("Available options:");
        for (WebElement opt : options) {
          System.out.println("  - " + opt.getText() + " (value: " + opt.getAttribute("value") + ")");
        }
        throw new RuntimeException("Could not select DEPOSIT. Available options listed above.", e2);
      }
    }
    
    // Wait for amount input
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".form-group:nth-child(2) input[type='number']")));
    WebElement amountInput = driver.findElement(By.cssSelector(".form-group:nth-child(2) input[type='number']"));
    amountInput.click();
    amountInput.clear();
    amountInput.sendKeys("100.00");
    
    // Optional: Add description
    try {
      WebElement descriptionInput = driver.findElement(By.cssSelector(".form-group:nth-child(3) input[type='text'][placeholder*='description']"));
      if (descriptionInput.isDisplayed()) {
        descriptionInput.click();
        descriptionInput.sendKeys("Selenium test deposit");
      }
    } catch (Exception e) {
      // Description field not required
    }
    
    // Submit the form
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".transaction-form button[type='submit']")));
    driver.findElement(By.cssSelector(".transaction-form button[type='submit']")).click();
    
    // Wait for success message
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".alert-success")));
    
    // Verify success
    WebElement successAlert = driver.findElement(By.cssSelector(".alert-success"));
    assertTrue(successAlert.isDisplayed());
    
    // Logout
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".logout-btn")));
    driver.findElement(By.cssSelector(".logout-btn")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".login-container")));
  }
}
